### PR TITLE
STRWEB-8 support loading CSV files

### PR DESCRIPTION
**Pull request by MikeTaylor**

### CODE REVIEW

**Review by mkuklis — APPROVED** [review]

**Comment by mkuklis** [comment]
👏

**Comment by MikeTaylor** [comment]
@mkuklis I would like to release this RSN, so my module that uses CSV resources can declare its need for them. Is there anything unusual involved in releasing it that I need to know, or should I just use the regular process?

**Comment by mkuklis** [comment]
@MikeTaylor as long as this is not a major version bump (which I don't think it is in this case) everything should be pretty straightforward here. I think we can release `v1.3.0` right?

**Comment by MikeTaylor** [comment]
OK, good — I will do that.

**Pull request merged**
