### PR TITLE
STRWEB-90 omit css alias cruft

### PR DESCRIPTION
**Pull request by zburke**
Don't manipulate `config.resolve.extensions` for the benefit of CSS because it appears we're not actually leveraging it anywhere. Additional spot-testing across a variety of applications doesn't show any of the odd problems we saw when we first tried to clean this up in [STRWEB-85](https://issues.folio.org/browse/STRWEB-85).

Refs [STRWEB-90](https://issues.folio.org/browse/STRWEB-90)

### CODE REVIEW

**Review by artem-blazhko — APPROVED** [review]

**Review by UladzislauKutarkin — APPROVED** [review]

**Comment by zburke** [comment]
@JohnC-80, @EthanFreestone, I would love for you two to weigh in on this.

**Comment by EthanFreestone** [comment]
> @JohnC-80, @EthanFreestone, I would love for you two to weigh in on this.

Apologies for the later reply, only just saw this. Change looks good to me, have tested locally without incident so AFAIC it's good to go :D

**Review by EthanFreestone — APPROVED** [review]

**Comment by zburke** [comment]
Thanks, @EthanFreestone. Can you or @JohnC-80 also approve #130 so I can get the version bumped on master? I'll merge this as soon as that is taken care of.

**Comment by EthanFreestone** [comment]
> Thanks, @EthanFreestone. Can you or @JohnC-80 also approve #130 so I can get the version bumped on master? I'll merge this as soon as that is taken care of.

Have approved the version bump :)

**Review by JohnC-80 — APPROVED** [review]

**Pull request merged**
